### ISSUE TITLE
Windows Terminal [6.1.7601] - how to install dracula-theme on this version?

### ISSUE THREAD

**Issue by eduardo-raniero** [dracula/windows-terminal#12]
Hello there!
Recently i decided to install dracula-theme into my windows terminal, once i'm a big fan of the vscode version. But it seems that [tutorial](https://draculatheme.com/windows-terminal) it is made for a modern OS, and i'm have no clue how to install it. 

the version of my Windows, according to the cmd it is 6.1.7601:
![image](https://user-images.githubusercontent.com/73201589/135835010-0a7bcec5-c550-4e0f-8f99-fa08ab4bbd58.png)

**Comment by thismat** [comment]
Heya,

What you're using in the screenshot is Windows default "cmd" terminal, which is not the same as the updated "Windows Terminal". This repository is a theme for https://github.com/Microsoft/Terminal specifically. 

Thanks!

**Comment by eduardo-raniero** [comment]
@thismat Thanks for the help!
Sadly i won't be able to install it, because my OS version is not compatible.

> Note: Windows Terminal requires Windows 10 1903 (build 18362) or later
