### ISSUE TITLE
[Dracula PRO] PowerShell parameters are too dark

### ISSUE THREAD

**Issue by pyxelr** [dracula/windows-terminal#14]
I have observed that the colour of parameters passed in the PowerShell profile is too dark for Dracula PRO (it is not the case of the free Dracula).

Let me present a couple of examples with the `-Path` parameter. In all of them, I am applying 80% background opacity of Windows Terminal, where the situation gets slightly better if I would not apply it. Besides, I am using the starship prompt, which does not affect the colouring.

- Example 1 (focused window on a darker background):
![pro_focus](https://user-images.githubusercontent.com/30161753/165365155-e0ea2221-69b5-49de-bf5f-5b38440652e4.png)

- Example 2 (unfocused window on a darker background):
![pro_unfocus](https://user-images.githubusercontent.com/30161753/165365209-ec34c30c-3760-49c6-8392-48c1268f99d5.png)

- Example 3 (focused window on a brighter background):
![pro_bright_background](https://user-images.githubusercontent.com/30161753/165365247-25a3296a-860a-46b6-be32-276b94773632.png)

---

To improve the readability, I propose replacing `"brightBlack": "#504C67"` with `"brightBlack": "#8F89B4"`.
Here is the effect:

- Example 1 (focused window on a darker background):
![pro_modified_focus](https://user-images.githubusercontent.com/30161753/165366055-9b23a7b8-cd15-447d-a198-b8ba0976c667.png)

- Example 2 (unfocused window on a darker background):
![pro_modified_unfocus](https://user-images.githubusercontent.com/30161753/165366067-a660e27c-78c5-4083-be3f-db592d8fc907.png)

**Comment by thismat** [comment]
Thanks for the feedback. If I understand correctly this is related to the paid Dracula Pro windows terminal theme?

Your feedback would need to go to @zenorocha or maybe the ideas section of https://github.com/dracula/dracula-theme/discussions, currently this is the repository for the free Dracula theme. 

Thanks again!

**Comment by pyxelr** [comment]
@thismat: You are right, thanks for the suggestion. I have just opened up a discussion in the ideas section: https://github.com/dracula/dracula-theme/discussions/715

Therefore, feel free to close this issue.

**Comment by thismat** [comment]
Sounds good! Thanks and good luck!
