### ISSUE TITLE
Windows Terminal - Installation instructions look not finished

### ISSUE THREAD

**Issue by rumplin** [dracula/windows-terminal#16]
So I followed the instructions for the installation here: https://draculatheme.com/windows-terminal

The **Install** section explains how to open the _Settings_ of the _Windows Terminal_, but then suddenly it's talking about making changes to the `settings.json` file ?

Not explaining where to find it, or what to do in the Settings window.

**Comment by thismat** [comment]
Thanks. Windows Terminal has changed it's UI since that was written. I have updated the instructions to include the missing step.
