### ISSUE TITLE
Readme Problem

### ISSUE THREAD

**Issue by SarcasmAppreciated** [dracula/windows-terminal#3]
In the README, if you set the background property in the profiles section (not the colour scheme), you will overwrite any colours set in the colour schemes.

`"profiles" : 
    [
        {
            "acrylicOpacity" : 0.5,
            "background" : "#282A36"`

Should probably remove the background property.

**Comment by thismat** [comment]
Thanks @SarcasmAppreciated. I've updated the readme to resolve the issue.

**Comment by thismat** [comment]
Let me know if you find any other issues! 👍
