### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by byyxx128** [dracula/windows-terminal#6]
ㅤ

**Comment by thismat** [comment]
@byyxx128 I appreciate you noticing this. I believe some of those colors got changed inadvertently. I will get them patched shortly.

**Comment by thismat** [comment]
Actually, @byyxx128 this does match the spec. There seems to be one color that is off and I'm making that correction. Please see: https://spec.draculatheme.com/#sec-ANSI

This is the pallet from the spec being used for the terminal spec. What specifically is it you are taking exception to?

**Comment by thismat** [comment]
@byyxx128 The changes have been made to correct the issue. Thanks again for bringing it to my attention.
